// State: Index
export const UPDATE_INDEX_SCREEN = 'UPDATE_INDEX_SCREEN'

// State: Login
export const CLEAR_LOGIN_ERRORS = 'CLEAR_LOGIN_ERRORS'
export const UPDATE_LOGIN_EMAIL = 'UPDATE_LOGIN_EMAIL'
export const UPDATE_LOGIN_PASSWORD = 'UPDATE_LOGIN_PASSWORD'
export const VALIDATE_LOGIN_DATA = 'VALIDATE_LOGIN_DATA'

// State: Register
export const CLEAR_REGISTER_ERRORS = 'CLEAR_REGISTER_ERRORS'
export const UPDATE_REGISTER_EMAIL = 'UPDATE_REGISTER_EMAIL'
export const UPDATE_REGISTER_PASSWORD = 'UPDATE_REGISTER_PASSWORD'
export const UPDATE_REGISTER_RETYPE = 'UPDATE_REGISTER_RETYPE'
export const VALIDATE_REGISTER_DATA = 'VALIDATE_REGISTER_DATA'

// State: Logout
export const TOGGLE_LOGOUT_MODAL = 'TOGGLE_LOGOUT_MODAL'

// State: Reset
export const TOGGLE_RESET_MODAL = 'TOGGLE_RESET_MODAL'
export const UPDATE_OLD_PASSWORD = 'UPDATE_OLD_PASSWORD'
export const UPDATE_NEW_PASSWORD = 'UPDATE_NEW_PASSWORD'

// State: Analyser
export const UPDATE_SUPPORTED_LANGUAGES = 'UPDATE_SUPPORTED_LANGUAGES'
export const UPDATE_SNIPPET_HISTORY = 'UPDATE_SNIPPET_HISTORY'
export const UPDATE_SNIPPET_DATA = 'UPDATE_SNIPPET_DATA'
export const UPDATE_SNIPPET_LANGUAGE = 'UPDATE_SNIPPET_LANGUAGE'
export const UPDATE_SNIPPET_CONTENT = 'UPDATE_SNIPPET_CONTENT'
export const CLEAR_SNIPPET_DATA = 'CLEAR_SNIPPET_DATA'